name:
  simpleils

services:
  web:
    container_name: web
    image: simpleils-web:${TAG}
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: simpleils-db:${TAG}
    build: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: simpleils-nginx:${TAG}
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - 80:80

volumes:
  dbdata:
