name:
  simpleils

services:
  db:
    container_name: db
    image: simpleils-db:${TAG}
    build: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: simpleils
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: simpleils
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
