name:
  simpleils

services:
  web:
    container_name: web
    image: simpleils-web:${TAG}
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    ports:
      - 80:3000
  db:
    container_name: db
    image: simpleils-db:${TAG}
    build: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
